// Mock data for development — replace with Sanity CMS queries in production

export const breakingNewsItems = [
    { text: 'गढ़वा में भीषण सड़क हादसा, 3 लोगों की मौत, 8 घायल', href: '/news/garhwa-road-accident' },
    { text: 'पलामू में नक्सलियों की मुठभेड़, CRPF जवान घायल', href: '/news/palamu-naxal-encounter' },
    { text: 'झारखंड सरकार ने 5000 पदों पर भर्ती घोषित की', href: '/news/jharkhand-govt-jobs-5000' },
    { text: 'गढ़वा थाना क्षेत्र में चोरों का आतंक, 1 रात में 5 घटनाएं', href: '/news/garhwa-theft-spree' },
    { text: 'JP सीमेंट प्लांट में बड़ा हादसा, 2 मजदूर घायल', href: '/news/jp-cement-accident' },
    { text: 'पलामू में भारी बारिश, नदियां उफान पर, अलर्ट जारी', href: '/news/palamu-flood-alert' },
    { text: 'JPSC परीक्षा 2025 की तारीख घोषित, आवेदन शुरू', href: '/category/jobs' },
]

export const featuredArticles = [
    {
        title: 'गढ़वा में भीषण सड़क हादसा: NH-75 पर ट्रक-बस भिड़ंत, 3 मौत 8 घायल',
        slug: 'garhwa-nh75-truck-bus-accident',
        excerpt: 'गढ़वा जिले के NH-75 पर मंगलवार रात भीषण सड़क हादसा हुआ। एक ट्रक ने यात्री बस को सीधी टक्कर मारी जिसमें 3 लोगों की मौत हो गई और 8 घायल हैं।',
        featureImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
        author: 'राजेश कुमार',
    },
    {
        title: 'पलामू में CRPF-नक्सली मुठभेड़: 2 नक्सली ढेर, जवान सुरक्षित',
        slug: 'palamu-crpf-naxal-encounter',
        excerpt: 'पलामू के घने जंगलों में सोमवार को CRPF और नक्सलियों के बीच मुठभेड़ हुई। सर्च ऑपरेशन में 2 नक्सलियों को मार गिराया गया।',
        featureImage: 'https://images.unsplash.com/photo-1601933973783-43cf8a7d4c5f?w=800&h=500&fit=crop',
        category: 'राजनीति',
        categorySlug: 'politics',
        district: 'palamu',
        publishedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
        author: 'मोहन सिंह',
    },
    {
        title: 'झारखंड में 5000 सरकारी पदों पर भर्ती, 10वीं पास करें आवेदन',
        slug: 'jharkhand-govt-jobs-5000-posts',
        excerpt: 'झारखंड सरकार ने विभिन्न विभागों में 5000 पदों पर भर्ती का एलान किया है। 10वीं और 12वीं पास उम्मीदवार आवेदन कर सकते हैं।',
        featureImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=500&fit=crop',
        category: 'नौकरी',
        categorySlug: 'jobs',
        district: 'jharkhand',
        publishedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
        author: 'सुनील कुमार',
    },
]

export const garhwaNews = [
    {
        title: 'गढ़वा सदर अस्पताल में डॉक्टरों की कमी, मरीज परेशान',
        slug: 'garhwa-hospital-doctors-shortage',
        excerpt: 'गढ़वा सदर अस्पताल में विशेषज्ञ डॉक्टरों के पद रिक्त हैं, जिससे मरीजों को इलाज के लिए रांची जाना पड़ रहा है।',
        featureImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400&h=250&fit=crop',
        category: 'स्थानीय',
        categorySlug: 'garhwa',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
        author: 'अमित पाठक',
    },
    {
        title: 'गढ़वा में मतदान शांतिपूर्ण संपन्न, 72% वोटिंग',
        slug: 'garhwa-election-72-percent-voting',
        excerpt: 'गढ़वा विधानसभा उपचुनाव में 72 प्रतिशत मतदान हुआ। सभी बूथों पर शांतिपूर्ण माहौल रहा।',
        featureImage: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=400&h=250&fit=crop',
        category: 'राजनीति',
        categorySlug: 'politics',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
        author: 'राम नारायण',
    },
    {
        title: 'गढ़वा रेलवे स्टेशन के विकास के लिए 15 करोड़ की मंजूरी',
        slug: 'garhwa-railway-station-15-crore',
        excerpt: 'गढ़वा रोड रेलवे स्टेशन के आधुनिकीकरण के लिए रेलवे मंत्रालय ने 15 करोड़ रुपए की मंजूरी दी है।',
        featureImage: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400&h=250&fit=crop',
        category: 'विकास',
        categorySlug: 'garhwa',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
        author: 'सुरेश यादव',
    },
    {
        title: 'गढ़वा पुलिस की बड़ी कार्रवाई: 5 शातिर चोर गिरफ्तार',
        slug: 'garhwa-police-5-thieves-arrested',
        excerpt: 'गढ़वा पुलिस ने एक विशेष अभियान में शातिर चोरों के एक गिरोह को गिरफ्तार किया। बड़ी मात्रा में चोरी का सामान बरामद।',
        featureImage: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400&h=250&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
        author: 'विकास तिवारी',
    },
]

export const palamuNews = [
    {
        title: 'पलामू में बाढ़ का खतरा: कोयल नदी खतरे के निशान पर',
        slug: 'palamu-koyal-river-flood-danger',
        excerpt: 'लगातार बारिश से पलामू में कोयल नदी खतरे के निशान पर है। जिला प्रशासन ने अलर्ट जारी किया है।',
        featureImage: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&h=250&fit=crop',
        category: 'स्थानीय',
        categorySlug: 'palamu',
        district: 'palamu',
        publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
        author: 'देव प्रकाश',
    },
    {
        title: 'पलामू में दुकानों में चोरी: 3 आरोपी गिरफ्तार, माल बरामद',
        slug: 'palamu-shop-theft-3-arrested',
        excerpt: 'पलामू के बाजार क्षेत्र में तीन दुकानों में हुई चोरी की घटना में पुलिस ने 3 आरोपियों को गिरफ्तार किया।',
        featureImage: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=250&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'palamu',
        publishedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
        author: 'प्रकाश चंद्र',
    },
    {
        title: 'मेदिनीनगर में नई बस सेवा शुरू, पलामू-रांची सीधा कनेक्शन',
        slug: 'medininagar-new-bus-service-ranchi',
        excerpt: 'पलामू के यात्रियों के लिए खुशखबरी। मेदिनीनगर से रांची के लिए सीधी बस सेवा शुरू हो गई है।',
        featureImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&h=250&fit=crop',
        category: 'परिवहन',
        categorySlug: 'palamu',
        district: 'palamu',
        publishedAt: new Date(Date.now() - 10 * 3600000).toISOString(),
        author: 'राजीव रंजन',
    },
]

export const latestJobs = [
    {
        title: 'झारखंड पुलिस कांस्टेबल भर्ती 2025',
        posts: '1200 पद',
        qualification: '10वीं पास',
        lastDate: '15 मार्च 2025',
        href: '/news/jharkhand-police-constable-2025',
        badge: '🚨',
        color: 'bg-red-50 border-red-200',
    },
    {
        title: 'JPSC PT परीक्षा 2025 — 342 पदों के लिए',
        posts: '342 पद',
        qualification: 'स्नातक',
        lastDate: '20 मार्च 2025',
        href: '/news/jpsc-pt-2025',
        badge: '📋',
        color: 'bg-blue-50 border-blue-200',
    },
    {
        title: 'गढ़वा नगर पालिका में ठेका कर्मचारी भर्ती',
        posts: '45 पद',
        qualification: '8वीं पास',
        lastDate: '28 फरवरी 2025',
        href: '/news/garhwa-nagar-palika-bharti',
        badge: '🏢',
        color: 'bg-green-50 border-green-200',
    },
    {
        title: 'रांची जिला न्यायालय में क्लर्क भर्ती',
        posts: '56 पद',
        qualification: '12वीं पास',
        lastDate: '5 मार्च 2025',
        href: '/news/ranchi-court-clerk-bharti',
        badge: '⚖️',
        color: 'bg-yellow-50 border-yellow-200',
    },
    {
        title: 'NREGA लेखाकार भर्ती — झारखंड के सभी जिले',
        posts: '180 पद',
        qualification: '10वीं / 12वीं',
        lastDate: '10 मार्च 2025',
        href: '/news/nrega-lekhakar-bharti',
        badge: '📊',
        color: 'bg-purple-50 border-purple-200',
    },
    {
        title: 'आंगनवाड़ी सहायिका भर्ती — पलामू जिला',
        posts: '320 पद',
        qualification: '8वीं पास',
        lastDate: '12 मार्च 2025',
        href: '/news/palamu-anganwadi-bharti',
        badge: '👶',
        color: 'bg-pink-50 border-pink-200',
    },
]

export const crimeNews = [
    {
        title: 'गढ़वा में युवक की हत्या, परिजनों ने लगाया आरोप',
        slug: 'garhwa-youth-murder',
        excerpt: '',
        featureImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=250&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'garhwa',
        publishedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
        author: 'संवाददाता',
    },
    {
        title: 'पलामू में महिला से लूट, बाइक सवार अपराधी फरार',
        slug: 'palamu-woman-loot',
        excerpt: '',
        featureImage: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&h=250&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'palamu',
        publishedAt: new Date(Date.now() - 7 * 3600000).toISOString(),
        author: 'संवाददाता',
    },
    {
        title: 'झारखंड: साइबर ठगी के आरोपी गिरफ्तार, 5 लाख की ठगी',
        slug: 'jharkhand-cyber-fraud-arrested',
        excerpt: '',
        featureImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        category: 'अपराध',
        categorySlug: 'crime',
        district: 'jharkhand',
        publishedAt: new Date(Date.now() - 14 * 3600000).toISOString(),
        author: 'संवाददाता',
    },
]

export const popularArticles = [
    { title: 'गढ़वा में पेट्रोल पंप लूट: CCTV में कैद हुए आरोपी', slug: 'garhwa-petrol-pump-loot', publishedAt: new Date(Date.now() - 24 * 3600000).toISOString() },
    { title: 'पलामू टाइगर रिजर्व में बाघ की दहाड़, ग्रामीण भयभीत', slug: 'palamu-tiger-sighting', publishedAt: new Date(Date.now() - 30 * 3600000).toISOString() },
    { title: 'JPSC PT 2025: इन विषयों से आएंगे प्रश्न', slug: 'jpsc-pt-2025-syllabus', publishedAt: new Date(Date.now() - 48 * 3600000).toISOString() },
    { title: 'गढ़वा: दलाल गिरोह का भंडाफोड़, 10 गिरफ्तार', slug: 'garhwa-dalal-gang-busted', publishedAt: new Date(Date.now() - 2 * 86400000).toISOString() },
    { title: 'झारखंड में नकल माफिया: परीक्षार्थी गिरफ्तार', slug: 'jharkhand-cheating-mafia', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString() },
]
